Repository pce-devel/mednafenPceDev, pull requests merged in 2022-04, with the labels that each got.

#13 Enhancement Video - Increase visible Scanline defaults
  mednafen/src/pce/pce.cpp
  mednafen/src/pce/vce.cpp
Labels: enhancement, good first issue, video

#14 Enhancement Audio - Change Audio defaults to match real hardware
  mednafen/src/pce/pce.cpp
Labels: enhancement, Audio

#16 Enhancement Video - Enable Horizontal Overscan
  mednafen/src/pce/pce.cpp
Labels: enhancement, video

#23 Various improvements to pcfx external memory handling ( #17 )
  mednafen/src/general.cpp
  mednafen/src/general.h
  mednafen/src/pcfx/mem-handler.inc
  mednafen/src/pcfx/pcfx.cpp
Labels: PC-FX, memory, improvement

#24 Fix CD head seek timing for PCE ( #4 )
  mednafen/src/Makefile.in
  mednafen/src/cdrom/Makefile.am.inc
  mednafen/src/cdrom/scsicd-pce-commands.inc
  mednafen/src/cdrom/scsicd.cpp
  mednafen/src/cdrom/seektime_pce.cpp
  mednafen/src/cdrom/seektime_pce.h
Labels: PCE CD/TG-16 CD, Accuracy
